/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type Link = {
  _type: 'link'
  label: string
  url: string
}

export type SocialLink = {
  _type: 'socialLink'
  platform: 'linkedin' | 'malt' | 'github' | 'x' | 'other'
  url: string
}

export type SkillGroup = {
  _type: 'skillGroup'
  title: string
  skills: Array<string>
}

export type Stat = {
  _type: 'stat'
  value: string
  label: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h2' | 'h3' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: string
      caption?: string
      _type: 'image'
      _key: string
    }
>

export type PortfolioFilter = {
  _id: string
  _type: 'portfolioFilter'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  value: string
}

export type Information = {
  _id: string
  _type: 'information'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  fullName: string
  thumbImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  largeImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  bio: string
  age?: number
  birthday?: string
  nationality?: string
  languages?: Array<string>
  address?: string
  freelance?: string
  isAvailable?: boolean
  availabilityMessage?: string
  socialAddress?: {
    github?: string
    linkedin?: string
    malt?: string
  }
  phoneNumbers?: Array<string>
  emailAddress?: Array<string>
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type ClientReview = {
  _id: string
  _type: 'clientReview'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  meta?: string
  givenreview?: number
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  text: string
}

export type EducationalBackground = {
  _id: string
  _type: 'educationalBackground'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  meta: string
  text?: string
  year: string
}

export type Service = {
  _id: string
  _type: 'service'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  text: string
  iconName?: 'code' | 'server' | 'mobile' | 'team' | 'layout' | 'gauge'
  order?: number
  icon?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type JobExperience = {
  _id: string
  _type: 'jobExperience'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  company: string
  companyUrl?: string
  location?: string
  contractType?: 'freelance' | 'permanent' | 'fixedTerm' | 'apprenticeship' | 'internship'
  startYear: number
  current?: boolean
  endYear?: number
  summary?: string
  achievements?: Array<string>
  tags?: Array<string>
  meta?: string
  year?: string
  text?: string
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  category: 'product' | 'webapp' | 'mobile' | 'website' | 'ecommerce' | 'sideproject'
  subtitle: string
  tags: Array<string>
  url?: string
  featured?: boolean
  order?: number
  client?: string
  role?: string
  period?: string
  keyResults?: Array<
    {
      _key: string
    } & Stat
  >
  body?: RichText
  links?: Array<
    {
      _key: string
    } & Link
  >
  coverimage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  imagegallery?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
  videogallery?: Array<string>
  filters?: Array<string>
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type Profile = {
  _id: string
  _type: 'profile'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  jobTitle: string
  availability?: {
    status: 'available' | 'limited' | 'unavailable'
    message?: string
  }
  headline: string
  headlineHighlight?: string
  intro: string
  stats?: Array<
    {
      _key: string
    } & Stat
  >
  portrait?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  about?: RichText
  location?: string
  languages?: Array<string>
  skillGroups?: Array<
    {
      _key: string
    } & SkillGroup
  >
  resume?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
  contactText?: string
  email: string
  phone?: string
  socialLinks?: Array<
    {
      _key: string
    } & SocialLink
  >
  seo?: {
    title?: string
    description?: string
  }
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Link
  | SocialLink
  | SkillGroup
  | Stat
  | SanityImageAssetReference
  | RichText
  | PortfolioFilter
  | Information
  | SanityImageCrop
  | SanityImageHotspot
  | ClientReview
  | EducationalBackground
  | Service
  | JobExperience
  | Project
  | Slug
  | SanityFileAssetReference
  | Profile
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: ../sanity/queries.ts
// Variable: SITE_QUERY
// Query: *[_type == "profile" && _id == "profile"][0]{    firstName,    lastName,    jobTitle,    headline,    intro,    email,    location,    availability,    socialLinks[]{_key, platform, url},    seo  }
export type SITE_QUERY_RESULT = {
  firstName: string
  lastName: string
  jobTitle: string
  headline: string
  intro: string
  email: string
  location: string | null
  availability: {
    status: 'available' | 'limited' | 'unavailable'
    message?: string
  } | null
  socialLinks: Array<{
    _key: string
    platform: 'github' | 'linkedin' | 'malt' | 'other' | 'x'
    url: string
  }> | null
  seo: {
    title?: string
    description?: string
  } | null
} | null

// Source: ../sanity/queries.ts
// Variable: HOME_QUERY
// Query: {  "profile": *[_type == "profile" && _id == "profile"][0]{    firstName,    lastName,    jobTitle,    availability,    headline,    headlineHighlight,    intro,    stats[]{_key, value, label},    portrait{  alt,  crop,  hotspot,  asset->{_id, url, metadata{lqip, dimensions{width, height}}}},    about,    location,    languages,    skillGroups[]{_key, title, skills},    "resumeUrl": resume.asset->url,    contactText,    email,    phone,    socialLinks[]{_key, platform, url}  },  "projects": *[_type == "project" && defined(slug.current)]    | order(coalesce(order, 999) asc, _createdAt asc){        _id,  title,  "slug": slug.current,  category,  subtitle,  tags,  url,  period,  "hasCaseStudy": defined(body[0]),  coverimage{  alt,  crop,  hotspot,  asset->{_id, url, metadata{lqip, dimensions{width, height}}}},      featured,      client,      keyResults[]{_key, value, label}    },  "experiences": *[_type == "jobExperience"]    | order(select(current == true => 9999, coalesce(endYear, startYear)) desc, startYear desc){      _id,      title,      company,      companyUrl,      location,      contractType,      startYear,      endYear,      current,      summary,      achievements,      tags    },  "services": *[_type == "service"] | order(coalesce(order, 999) asc){_id, title, text, iconName},  "education": *[_type == "educationalBackground"] | order(year desc){_id, title, meta, year},  "testimonials": *[_type == "clientReview"] | order(_createdAt desc){    _id,    name,    meta,    text,    image{  alt,  crop,  hotspot,  asset->{_id, url, metadata{lqip, dimensions{width, height}}}}  }}
export type HOME_QUERY_RESULT = {
  profile: {
    firstName: string
    lastName: string
    jobTitle: string
    availability: {
      status: 'available' | 'limited' | 'unavailable'
      message?: string
    } | null
    headline: string
    headlineHighlight: string | null
    intro: string
    stats: Array<{
      _key: string
      value: string
      label: string
    }> | null
    portrait: {
      alt: string | null
      crop: SanityImageCrop | null
      hotspot: SanityImageHotspot | null
      asset: {
        _id: string
        url: string
        metadata: {
          lqip: string | null
          dimensions: {
            width: number
            height: number
          } | null
        } | null
      } | null
    } | null
    about: RichText | null
    location: string | null
    languages: Array<string> | null
    skillGroups: Array<{
      _key: string
      title: string
      skills: Array<string>
    }> | null
    resumeUrl: string | null
    contactText: string | null
    email: string
    phone: string | null
    socialLinks: Array<{
      _key: string
      platform: 'github' | 'linkedin' | 'malt' | 'other' | 'x'
      url: string
    }> | null
  } | null
  projects: Array<{
    _id: string
    title: string
    slug: string
    category: 'ecommerce' | 'mobile' | 'product' | 'sideproject' | 'webapp' | 'website'
    subtitle: string
    tags: Array<string>
    url: string | null
    period: string | null
    hasCaseStudy: false | true
    coverimage: {
      alt: string | null
      crop: SanityImageCrop | null
      hotspot: SanityImageHotspot | null
      asset: {
        _id: string
        url: string
        metadata: {
          lqip: string | null
          dimensions: {
            width: number
            height: number
          } | null
        } | null
      } | null
    }
    featured: boolean | null
    client: string | null
    keyResults: Array<{
      _key: string
      value: string
      label: string
    }> | null
  }>
  experiences: Array<{
    _id: string
    title: string
    company: string
    companyUrl: string | null
    location: string | null
    contractType: 'apprenticeship' | 'fixedTerm' | 'freelance' | 'internship' | 'permanent' | null
    startYear: number
    endYear: number | null
    current: boolean | null
    summary: string | null
    achievements: Array<string> | null
    tags: Array<string> | null
  }>
  services: Array<{
    _id: string
    title: string
    text: string
    iconName: 'code' | 'gauge' | 'layout' | 'mobile' | 'server' | 'team' | null
  }>
  education: Array<{
    _id: string
    title: string
    meta: string
    year: string
  }>
  testimonials: Array<{
    _id: string
    name: string
    meta: string | null
    text: string
    image: {
      alt: null
      crop: SanityImageCrop | null
      hotspot: SanityImageHotspot | null
      asset: {
        _id: string
        url: string
        metadata: {
          lqip: string | null
          dimensions: {
            width: number
            height: number
          } | null
        } | null
      } | null
    } | null
  }>
}

// Source: ../sanity/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  category,  subtitle,  tags,  url,  period,  "hasCaseStudy": defined(body[0]),  coverimage{  alt,  crop,  hotspot,  asset->{_id, url, metadata{lqip, dimensions{width, height}}}},    _updatedAt,    client,    role,    keyResults[]{_key, value, label},    links[]{_key, label, url},    body[]{      ...,      _type == "image" => {        _key,        _type,        caption,          alt,  crop,  hotspot,  asset->{_id, url, metadata{lqip, dimensions{width, height}}}      }    },    imagegallery[]{_key,   alt,  crop,  hotspot,  asset->{_id, url, metadata{lqip, dimensions{width, height}}}},    "others": *[_type == "project" && defined(slug.current) && slug.current != $slug]      | order(coalesce(order, 999) asc)[0...3]{  _id,  title,  "slug": slug.current,  category,  subtitle,  tags,  url,  period,  "hasCaseStudy": defined(body[0]),  coverimage{  alt,  crop,  hotspot,  asset->{_id, url, metadata{lqip, dimensions{width, height}}}}}  }
export type PROJECT_QUERY_RESULT = {
  _id: string
  title: string
  slug: string
  category: 'ecommerce' | 'mobile' | 'product' | 'sideproject' | 'webapp' | 'website'
  subtitle: string
  tags: Array<string>
  url: string | null
  period: string | null
  hasCaseStudy: false | true
  coverimage: {
    alt: string | null
    crop: SanityImageCrop | null
    hotspot: SanityImageHotspot | null
    asset: {
      _id: string
      url: string
      metadata: {
        lqip: string | null
        dimensions: {
          width: number
          height: number
        } | null
      } | null
    } | null
  }
  _updatedAt: string
  client: string | null
  role: string | null
  keyResults: Array<{
    _key: string
    value: string
    label: string
  }> | null
  links: Array<{
    _key: string
    label: string
    url: string
  }> | null
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h2' | 'h3' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset: {
          _id: string
          url: string
          metadata: {
            lqip: string | null
            dimensions: {
              width: number
              height: number
            } | null
          } | null
        } | null
        media?: unknown
        hotspot: SanityImageHotspot | null
        crop: SanityImageCrop | null
        alt: string
        caption: string | null
        _type: 'image'
        _key: string
      }
  > | null
  imagegallery: Array<{
    _key: string
    alt: string | null
    crop: SanityImageCrop | null
    hotspot: SanityImageHotspot | null
    asset: {
      _id: string
      url: string
      metadata: {
        lqip: string | null
        dimensions: {
          width: number
          height: number
        } | null
      } | null
    } | null
  }> | null
  others: Array<{
    _id: string
    title: string
    slug: string
    category: 'ecommerce' | 'mobile' | 'product' | 'sideproject' | 'webapp' | 'website'
    subtitle: string
    tags: Array<string>
    url: string | null
    period: string | null
    hasCaseStudy: false | true
    coverimage: {
      alt: string | null
      crop: SanityImageCrop | null
      hotspot: SanityImageHotspot | null
      asset: {
        _id: string
        url: string
        metadata: {
          lqip: string | null
          dimensions: {
            width: number
            height: number
          } | null
        } | null
      } | null
    }
  }>
} | null

// Source: ../sanity/queries.ts
// Variable: CASE_STUDIES_QUERY
// Query: *[_type == "project" && defined(slug.current) && defined(body[0])]{    "slug": slug.current,    _updatedAt  }
export type CASE_STUDIES_QUERY_RESULT = Array<{
  slug: string
  _updatedAt: string
}>

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "profile" && _id == "profile"][0]{\n    firstName,\n    lastName,\n    jobTitle,\n    headline,\n    intro,\n    email,\n    location,\n    availability,\n    socialLinks[]{_key, platform, url},\n    seo\n  }\n': SITE_QUERY_RESULT
    '{\n  "profile": *[_type == "profile" && _id == "profile"][0]{\n    firstName,\n    lastName,\n    jobTitle,\n    availability,\n    headline,\n    headlineHighlight,\n    intro,\n    stats[]{_key, value, label},\n    portrait{\n  alt,\n  crop,\n  hotspot,\n  asset->{_id, url, metadata{lqip, dimensions{width, height}}}\n},\n    about,\n    location,\n    languages,\n    skillGroups[]{_key, title, skills},\n    "resumeUrl": resume.asset->url,\n    contactText,\n    email,\n    phone,\n    socialLinks[]{_key, platform, url}\n  },\n  "projects": *[_type == "project" && defined(slug.current)]\n    | order(coalesce(order, 999) asc, _createdAt asc){\n      \n  _id,\n  title,\n  "slug": slug.current,\n  category,\n  subtitle,\n  tags,\n  url,\n  period,\n  "hasCaseStudy": defined(body[0]),\n  coverimage{\n  alt,\n  crop,\n  hotspot,\n  asset->{_id, url, metadata{lqip, dimensions{width, height}}}\n}\n,\n      featured,\n      client,\n      keyResults[]{_key, value, label}\n    },\n  "experiences": *[_type == "jobExperience"]\n    | order(select(current == true => 9999, coalesce(endYear, startYear)) desc, startYear desc){\n      _id,\n      title,\n      company,\n      companyUrl,\n      location,\n      contractType,\n      startYear,\n      endYear,\n      current,\n      summary,\n      achievements,\n      tags\n    },\n  "services": *[_type == "service"] | order(coalesce(order, 999) asc){_id, title, text, iconName},\n  "education": *[_type == "educationalBackground"] | order(year desc){_id, title, meta, year},\n  "testimonials": *[_type == "clientReview"] | order(_createdAt desc){\n    _id,\n    name,\n    meta,\n    text,\n    image{\n  alt,\n  crop,\n  hotspot,\n  asset->{_id, url, metadata{lqip, dimensions{width, height}}}\n}\n  }\n}': HOME_QUERY_RESULT
    '\n  *[_type == "project" && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  "slug": slug.current,\n  category,\n  subtitle,\n  tags,\n  url,\n  period,\n  "hasCaseStudy": defined(body[0]),\n  coverimage{\n  alt,\n  crop,\n  hotspot,\n  asset->{_id, url, metadata{lqip, dimensions{width, height}}}\n}\n,\n    _updatedAt,\n    client,\n    role,\n    keyResults[]{_key, value, label},\n    links[]{_key, label, url},\n    body[]{\n      ...,\n      _type == "image" => {\n        _key,\n        _type,\n        caption,\n        \n  alt,\n  crop,\n  hotspot,\n  asset->{_id, url, metadata{lqip, dimensions{width, height}}}\n\n      }\n    },\n    imagegallery[]{_key, \n  alt,\n  crop,\n  hotspot,\n  asset->{_id, url, metadata{lqip, dimensions{width, height}}}\n},\n    "others": *[_type == "project" && defined(slug.current) && slug.current != $slug]\n      | order(coalesce(order, 999) asc)[0...3]{\n  _id,\n  title,\n  "slug": slug.current,\n  category,\n  subtitle,\n  tags,\n  url,\n  period,\n  "hasCaseStudy": defined(body[0]),\n  coverimage{\n  alt,\n  crop,\n  hotspot,\n  asset->{_id, url, metadata{lqip, dimensions{width, height}}}\n}\n}\n  }\n': PROJECT_QUERY_RESULT
    '\n  *[_type == "project" && defined(slug.current) && defined(body[0])]{\n    "slug": slug.current,\n    _updatedAt\n  }\n': CASE_STUDIES_QUERY_RESULT
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module '@sanity/client' {
  interface SanityQueries extends globalThis.SanityQueries {}
}
